spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wrxjsnu529.mysql.rds.aliyuncs.com:3307/myjd?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: wrx_jsnu
    password: 1515206+++520rjw
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 15
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 30000
      pool-name: HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis:
  type-aliases-package: com.jsnu.jd.jsnujd.pojo
  mapper-locations: classpath:mybatis/mapper/*.xml
server:
  port: 13505